"""for testing added a feild in event model 

Revision ID: 1d53d8d23613
Revises: 2af4b7543c53
Create Date: 2025-12-03 16:46:50.742646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d53d8d23613'
down_revision: Union[str, Sequence[str], None] = '2af4b7543c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('compliance_policy_documents_uploaded_by_fkey'), 'compliance_policy_documents', type_='foreignkey')
    op.drop_constraint(op.f('compliance_policy_documents_policy_set_id_fkey'), 'compliance_policy_documents', type_='foreignkey')
    op.create_foreign_key(None, 'compliance_policy_documents', 'users', ['uploaded_by'], ['id'], source_schema='testdb', referent_schema='testdb')
    op.create_foreign_key(None, 'compliance_policy_documents', 'compliance_policy_sets', ['policy_set_id'], ['id'], source_schema='testdb', referent_schema='testdb')
    op.alter_column('compliance_policy_sets', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'archived', name='policy_set_status'),
               type_=sa.Enum('draft', 'active', 'archived', name='policy_set_status', schema='testdb'),
               existing_nullable=True)
    op.drop_constraint(op.f('compliance_policy_sets_created_by_fkey'), 'compliance_policy_sets', type_='foreignkey')
    op.create_foreign_key(None, 'compliance_policy_sets', 'users', ['created_by'], ['id'], source_schema='testdb', referent_schema='testdb')
    op.alter_column('compliance_rules', 'rule_type',
               existing_type=postgresql.ENUM('do', 'dont', name='rule_type_enum'),
               type_=sa.Enum('do', 'dont', name='rule_type_enum', schema='testdb'),
               existing_nullable=True)
    op.alter_column('compliance_rules', 'severity',
               existing_type=postgresql.ENUM('info', 'low', 'medium', 'high', 'critical', name='severity_enum'),
               type_=sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_enum', schema='testdb'),
               existing_nullable=True)
    op.drop_constraint(op.f('compliance_rules_created_by_fkey'), 'compliance_rules', type_='foreignkey')
    op.drop_constraint(op.f('compliance_rules_policy_set_id_fkey'), 'compliance_rules', type_='foreignkey')
    op.create_foreign_key(None, 'compliance_rules', 'compliance_policy_sets', ['policy_set_id'], ['id'], source_schema='testdb', referent_schema='testdb', ondelete='CASCADE')
    op.create_foreign_key(None, 'compliance_rules', 'users', ['created_by'], ['id'], source_schema='testdb', referent_schema='testdb')
    op.add_column('conversation_events', sa.Column('test_column', sa.String(), nullable=True))
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], source_schema='testdb', referent_schema='testdb', ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], source_schema='testdb', referent_schema='testdb', ondelete='CASCADE')
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], source_schema='testdb', referent_schema='testdb', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], source_schema='testdb', referent_schema='testdb', ondelete='CASCADE')
    op.drop_constraint(op.f('user_tokens_user_id_fkey'), 'user_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_id'], ['id'], source_schema='testdb', referent_schema='testdb', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tokens', schema='testdb', type_='foreignkey')
    op.create_foreign_key(op.f('user_tokens_user_id_fkey'), 'user_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_roles', schema='testdb', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', schema='testdb', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'role_permissions', schema='testdb', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', schema='testdb', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('conversation_events', 'test_column')
    op.drop_constraint(None, 'compliance_rules', schema='testdb', type_='foreignkey')
    op.drop_constraint(None, 'compliance_rules', schema='testdb', type_='foreignkey')
    op.create_foreign_key(op.f('compliance_rules_policy_set_id_fkey'), 'compliance_rules', 'compliance_policy_sets', ['policy_set_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('compliance_rules_created_by_fkey'), 'compliance_rules', 'users', ['created_by'], ['id'])
    op.alter_column('compliance_rules', 'severity',
               existing_type=sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_enum', schema='testdb'),
               type_=postgresql.ENUM('info', 'low', 'medium', 'high', 'critical', name='severity_enum'),
               existing_nullable=True)
    op.alter_column('compliance_rules', 'rule_type',
               existing_type=sa.Enum('do', 'dont', name='rule_type_enum', schema='testdb'),
               type_=postgresql.ENUM('do', 'dont', name='rule_type_enum'),
               existing_nullable=True)
    op.drop_constraint(None, 'compliance_policy_sets', schema='testdb', type_='foreignkey')
    op.create_foreign_key(op.f('compliance_policy_sets_created_by_fkey'), 'compliance_policy_sets', 'users', ['created_by'], ['id'])
    op.alter_column('compliance_policy_sets', 'status',
               existing_type=sa.Enum('draft', 'active', 'archived', name='policy_set_status', schema='testdb'),
               type_=postgresql.ENUM('draft', 'active', 'archived', name='policy_set_status'),
               existing_nullable=True)
    op.drop_constraint(None, 'compliance_policy_documents', schema='testdb', type_='foreignkey')
    op.drop_constraint(None, 'compliance_policy_documents', schema='testdb', type_='foreignkey')
    op.create_foreign_key(op.f('compliance_policy_documents_policy_set_id_fkey'), 'compliance_policy_documents', 'compliance_policy_sets', ['policy_set_id'], ['id'])
    op.create_foreign_key(op.f('compliance_policy_documents_uploaded_by_fkey'), 'compliance_policy_documents', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###
