"""conversation events -1

Revision ID: 2c1482a5811c
Revises: f158f22e37a0
Create Date: 2025-12-01 09:51:41.587189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c1482a5811c'
down_revision: Union[str, Sequence[str], None] = 'f158f22e37a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index('idx_user_conversation', 'conversation_events', ['user_id', 'conversation_id'], unique=False, schema='ghostagent')
    op.create_index(op.f('ix_ghostagent_conversation_events_call_id'), 'conversation_events', ['call_id'], unique=False, schema='ghostagent')
    op.create_index(op.f('ix_ghostagent_conversation_events_conversation_id'), 'conversation_events', ['conversation_id'], unique=False, schema='ghostagent')
    op.create_index(op.f('ix_ghostagent_conversation_events_received_at'), 'conversation_events', ['received_at'], unique=False, schema='ghostagent')
    op.create_index(op.f('ix_ghostagent_conversation_events_user_id'), 'conversation_events', ['user_id'], unique=False, schema='ghostagent')
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index(op.f('ix_ghostagent_permissions_code'), 'permissions', ['code'], unique=True, schema='ghostagent')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index(op.f('ix_ghostagent_roles_name'), 'roles', ['name'], unique=True, schema='ghostagent')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index(op.f('ix_ghostagent_users_email'), 'users', ['email'], unique=True, schema='ghostagent')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['ghostagent.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ghostagent.roles.id'], ondelete='CASCADE'),
    schema='ghostagent'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ghostagent.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ghostagent.users.id'], ondelete='CASCADE'),
    schema='ghostagent'
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('access_token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ghostagent.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index(op.f('ix_ghostagent_user_tokens_access_token'), 'user_tokens', ['access_token'], unique=True, schema='ghostagent')
    op.create_index(op.f('ix_ghostagent_user_tokens_refresh_token'), 'user_tokens', ['refresh_token'], unique=True, schema='ghostagent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ghostagent_user_tokens_refresh_token'), table_name='user_tokens', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_user_tokens_access_token'), table_name='user_tokens', schema='ghostagent')
    op.drop_table('user_tokens', schema='ghostagent')
    op.drop_table('user_roles', schema='ghostagent')
    op.drop_table('role_permissions', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_users_email'), table_name='users', schema='ghostagent')
    op.drop_table('users', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_roles_name'), table_name='roles', schema='ghostagent')
    op.drop_table('roles', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_permissions_code'), table_name='permissions', schema='ghostagent')
    op.drop_table('permissions', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_conversation_events_user_id'), table_name='conversation_events', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_conversation_events_received_at'), table_name='conversation_events', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_conversation_events_conversation_id'), table_name='conversation_events', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_conversation_events_call_id'), table_name='conversation_events', schema='ghostagent')
    op.drop_index('idx_user_conversation', table_name='conversation_events', schema='ghostagent')
    op.drop_table('conversation_events', schema='ghostagent')
    # ### end Alembic commands ###
