"""added test feild

Revision ID: 3bef42fb5907
Revises: 447050d5fa0f
Create Date: 2025-12-06 19:35:45.479194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bef42fb5907'
down_revision: Union[str, Sequence[str], None] = '447050d5fa0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_testdb_compliance_policy_sets_created_by'), 'compliance_policy_sets', ['created_by'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_compliance_policy_sets_status'), 'compliance_policy_sets', ['status'], unique=False, schema='testdb')
    op.add_column('conversation_events', sa.Column('test_column', sa.String(), nullable=True), schema='testdb')
    op.alter_column('conversation_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='testdb')
    op.create_index(op.f('ix_testdb_conversation_events_event_type'), 'conversation_events', ['event_type'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_user_tokens_access_token_expiry'), 'user_tokens', ['access_token_expiry'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_user_tokens_is_revoked'), 'user_tokens', ['is_revoked'], unique=False, schema='testdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testdb_user_tokens_is_revoked'), table_name='user_tokens', schema='testdb')
    op.drop_index(op.f('ix_testdb_user_tokens_access_token_expiry'), table_name='user_tokens', schema='testdb')
    op.drop_index(op.f('ix_testdb_conversation_events_event_type'), table_name='conversation_events', schema='testdb')
    op.alter_column('conversation_events', 'received_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='testdb')
    op.drop_column('conversation_events', 'test_column', schema='testdb')
    op.drop_index(op.f('ix_testdb_compliance_policy_sets_status'), table_name='compliance_policy_sets', schema='testdb')
    op.drop_index(op.f('ix_testdb_compliance_policy_sets_created_by'), table_name='compliance_policy_sets', schema='testdb')
    # ### end Alembic commands ###