"""add compliance tables

Revision ID: 52db74776eb9
Revises: 37abcd61920c
Create Date: 2025-12-01 16:47:29.958963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52db74776eb9'
down_revision: Union[str, Sequence[str], None] = '37abcd61920c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index(op.f('ix_ghostagent_permissions_code'), 'permissions', ['code'], unique=True, schema='ghostagent')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index(op.f('ix_ghostagent_roles_name'), 'roles', ['name'], unique=True, schema='ghostagent')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index(op.f('ix_ghostagent_users_email'), 'users', ['email'], unique=True, schema='ghostagent')
    op.create_table('compliance_policy_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='policysetstatus'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['ghostagent.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['ghostagent.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ghostagent.roles.id'], ondelete='CASCADE'),
    schema='ghostagent'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ghostagent.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ghostagent.users.id'], ondelete='CASCADE'),
    schema='ghostagent'
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('access_token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ghostagent.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_index(op.f('ix_ghostagent_user_tokens_access_token'), 'user_tokens', ['access_token'], unique=True, schema='ghostagent')
    op.create_index(op.f('ix_ghostagent_user_tokens_refresh_token'), 'user_tokens', ['refresh_token'], unique=True, schema='ghostagent')
    op.create_table('compliance_policy_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_set_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_set_id'], ['ghostagent.compliance_policy_sets.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['ghostagent.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_set_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('rule_type', sa.Enum('do', 'dont', name='ruletype'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('example_snippets', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['ghostagent.users.id'], ),
    sa.ForeignKeyConstraint(['policy_set_id'], ['ghostagent.compliance_policy_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ghostagent'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_rules', schema='ghostagent')
    op.drop_table('compliance_policy_documents', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_user_tokens_refresh_token'), table_name='user_tokens', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_user_tokens_access_token'), table_name='user_tokens', schema='ghostagent')
    op.drop_table('user_tokens', schema='ghostagent')
    op.drop_table('user_roles', schema='ghostagent')
    op.drop_table('role_permissions', schema='ghostagent')
    op.drop_table('compliance_policy_sets', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_users_email'), table_name='users', schema='ghostagent')
    op.drop_table('users', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_roles_name'), table_name='roles', schema='ghostagent')
    op.drop_table('roles', schema='ghostagent')
    op.drop_index(op.f('ix_ghostagent_permissions_code'), table_name='permissions', schema='ghostagent')
    op.drop_table('permissions', schema='ghostagent')
    # ### end Alembic commands ###
