"""initial migration

Revision ID: 920638ae8f20
Revises: 
Create Date: 2025-12-09 16:43:36.951767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '920638ae8f20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_index('idx_user_conversation', 'conversation_events', ['user_id', 'conversation_id'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_conversation_events_conversation_id'), 'conversation_events', ['conversation_id'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_conversation_events_event_type'), 'conversation_events', ['event_type'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_conversation_events_received_at'), 'conversation_events', ['received_at'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_conversation_events_user_id'), 'conversation_events', ['user_id'], unique=False, schema='testdb')
    op.create_table('conversation_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('customer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_evaluated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_index('idx_conversation_log_ended_at', 'conversation_log', ['ended_at'], unique=False, schema='testdb')
    op.create_index('idx_conversation_log_is_evaluated', 'conversation_log', ['is_evaluated'], unique=False, schema='testdb')
    op.create_index('idx_user_conversation_log', 'conversation_log', ['user_id', 'conversation_id'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_conversation_log_conversation_id'), 'conversation_log', ['conversation_id'], unique=True, schema='testdb')
    op.create_index(op.f('ix_testdb_conversation_log_ended_at'), 'conversation_log', ['ended_at'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_conversation_log_user_id'), 'conversation_log', ['user_id'], unique=False, schema='testdb')
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_index(op.f('ix_testdb_permissions_code'), 'permissions', ['code'], unique=True, schema='testdb')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_index(op.f('ix_testdb_roles_name'), 'roles', ['name'], unique=True, schema='testdb')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_index(op.f('ix_testdb_users_email'), 'users', ['email'], unique=True, schema='testdb')
    op.create_table('compliance_policy_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='policy_set_status', schema='testdb'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['testdb.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_index(op.f('ix_testdb_compliance_policy_sets_created_by'), 'compliance_policy_sets', ['created_by'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_compliance_policy_sets_status'), 'compliance_policy_sets', ['status'], unique=False, schema='testdb')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['testdb.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['testdb.roles.id'], ondelete='CASCADE'),
    schema='testdb'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['testdb.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['testdb.users.id'], ondelete='CASCADE'),
    schema='testdb'
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('access_token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['testdb.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_index(op.f('ix_testdb_user_tokens_access_token'), 'user_tokens', ['access_token'], unique=True, schema='testdb')
    op.create_index(op.f('ix_testdb_user_tokens_access_token_expiry'), 'user_tokens', ['access_token_expiry'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_user_tokens_is_revoked'), 'user_tokens', ['is_revoked'], unique=False, schema='testdb')
    op.create_index(op.f('ix_testdb_user_tokens_refresh_token'), 'user_tokens', ['refresh_token'], unique=True, schema='testdb')
    op.create_table('compliance_policy_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_set_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_set_id'], ['testdb.compliance_policy_sets.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['testdb.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_set_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('rule_type', sa.Enum('do', 'dont', name='rule_type_enum', schema='testdb'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_enum', schema='testdb'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('example_snippets', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['testdb.users.id'], ),
    sa.ForeignKeyConstraint(['policy_set_id'], ['testdb.compliance_policy_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_table('conversation_compliance_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('policy_set_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('compliance_status', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('compliance_findings', sa.JSON(), nullable=True),
    sa.Column('violations_summary', sa.JSON(), nullable=True),
    sa.Column('applicable_rules_summary', sa.JSON(), nullable=True),
    sa.Column('llm_metadata', sa.JSON(), nullable=True),
    sa.Column('evaluated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluated_by_user_id'], ['testdb.users.id'], ),
    sa.ForeignKeyConstraint(['policy_set_id'], ['testdb.compliance_policy_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testdb'
    )
    op.create_index(op.f('ix_testdb_conversation_compliance_evaluations_conversation_id'), 'conversation_compliance_evaluations', ['conversation_id'], unique=False, schema='testdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testdb_conversation_compliance_evaluations_conversation_id'), table_name='conversation_compliance_evaluations', schema='testdb')
    op.drop_table('conversation_compliance_evaluations', schema='testdb')
    op.drop_table('compliance_rules', schema='testdb')
    op.drop_table('compliance_policy_documents', schema='testdb')
    op.drop_index(op.f('ix_testdb_user_tokens_refresh_token'), table_name='user_tokens', schema='testdb')
    op.drop_index(op.f('ix_testdb_user_tokens_is_revoked'), table_name='user_tokens', schema='testdb')
    op.drop_index(op.f('ix_testdb_user_tokens_access_token_expiry'), table_name='user_tokens', schema='testdb')
    op.drop_index(op.f('ix_testdb_user_tokens_access_token'), table_name='user_tokens', schema='testdb')
    op.drop_table('user_tokens', schema='testdb')
    op.drop_table('user_roles', schema='testdb')
    op.drop_table('role_permissions', schema='testdb')
    op.drop_index(op.f('ix_testdb_compliance_policy_sets_status'), table_name='compliance_policy_sets', schema='testdb')
    op.drop_index(op.f('ix_testdb_compliance_policy_sets_created_by'), table_name='compliance_policy_sets', schema='testdb')
    op.drop_table('compliance_policy_sets', schema='testdb')
    op.drop_index(op.f('ix_testdb_users_email'), table_name='users', schema='testdb')
    op.drop_table('users', schema='testdb')
    op.drop_index(op.f('ix_testdb_roles_name'), table_name='roles', schema='testdb')
    op.drop_table('roles', schema='testdb')
    op.drop_index(op.f('ix_testdb_permissions_code'), table_name='permissions', schema='testdb')
    op.drop_table('permissions', schema='testdb')
    op.drop_index(op.f('ix_testdb_conversation_log_user_id'), table_name='conversation_log', schema='testdb')
    op.drop_index(op.f('ix_testdb_conversation_log_ended_at'), table_name='conversation_log', schema='testdb')
    op.drop_index(op.f('ix_testdb_conversation_log_conversation_id'), table_name='conversation_log', schema='testdb')
    op.drop_index('idx_user_conversation_log', table_name='conversation_log', schema='testdb')
    op.drop_index('idx_conversation_log_is_evaluated', table_name='conversation_log', schema='testdb')
    op.drop_index('idx_conversation_log_ended_at', table_name='conversation_log', schema='testdb')
    op.drop_table('conversation_log', schema='testdb')
    op.drop_index(op.f('ix_testdb_conversation_events_user_id'), table_name='conversation_events', schema='testdb')
    op.drop_index(op.f('ix_testdb_conversation_events_received_at'), table_name='conversation_events', schema='testdb')
    op.drop_index(op.f('ix_testdb_conversation_events_event_type'), table_name='conversation_events', schema='testdb')
    op.drop_index(op.f('ix_testdb_conversation_events_conversation_id'), table_name='conversation_events', schema='testdb')
    op.drop_index('idx_user_conversation', table_name='conversation_events', schema='testdb')
    op.drop_table('conversation_events', schema='testdb')
    # ### end Alembic commands ###