"""removed test feild

Revision ID: ac561036462d
Revises: 3bef42fb5907
Create Date: 2025-12-06 19:46:50.046254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac561036462d'
down_revision: Union[str, Sequence[str], None] = '3bef42fb5907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_events', 'test_column', schema='testdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_events', sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True), schema='testdb')
    # ### end Alembic commands ###