"""removed test columns

Revision ID: eb3cb1cf662a
Revises: e60e11ca7c21
Create Date: 2025-12-08 08:59:07.608805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb3cb1cf662a'
down_revision: Union[str, Sequence[str], None] = 'e60e11ca7c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_policy_sets', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'archived', name='policy_set_status'),
               type_=sa.Enum('draft', 'active', 'archived', name='policy_set_status', schema='testghostagent'),
               existing_nullable=True,
               schema='testghostagent')
    op.alter_column('compliance_rules', 'rule_type',
               existing_type=postgresql.ENUM('do', 'dont', name='rule_type_enum'),
               type_=sa.Enum('do', 'dont', name='rule_type_enum', schema='testghostagent'),
               existing_nullable=True,
               schema='testghostagent')
    op.alter_column('compliance_rules', 'severity',
               existing_type=postgresql.ENUM('info', 'low', 'medium', 'high', 'critical', name='severity_enum'),
               type_=sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_enum', schema='testghostagent'),
               existing_nullable=True,
               schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_conversation_events_test_column'), table_name='conversation_events', schema='testghostagent')
    op.drop_column('conversation_events', 'test_column', schema='testghostagent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_events', sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=False), schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_conversation_events_test_column'), 'conversation_events', ['test_column'], unique=False, schema='testghostagent')
    op.alter_column('compliance_rules', 'severity',
               existing_type=sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_enum', schema='testghostagent'),
               type_=postgresql.ENUM('info', 'low', 'medium', 'high', 'critical', name='severity_enum'),
               existing_nullable=True,
               schema='testghostagent')
    op.alter_column('compliance_rules', 'rule_type',
               existing_type=sa.Enum('do', 'dont', name='rule_type_enum', schema='testghostagent'),
               type_=postgresql.ENUM('do', 'dont', name='rule_type_enum'),
               existing_nullable=True,
               schema='testghostagent')
    op.alter_column('compliance_policy_sets', 'status',
               existing_type=sa.Enum('draft', 'active', 'archived', name='policy_set_status', schema='testghostagent'),
               type_=postgresql.ENUM('draft', 'active', 'archived', name='policy_set_status'),
               existing_nullable=True,
               schema='testghostagent')
    # ### end Alembic commands ###