"""initial migration

Revision ID: fbb00de2bb42
Revises: 
Create Date: 2025-12-08 11:28:34.952716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbb00de2bb42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_column', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='testghostagent'
    )
    op.create_index('idx_user_conversation', 'conversation_events', ['user_id', 'conversation_id'], unique=False, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_conversation_events_conversation_id'), 'conversation_events', ['conversation_id'], unique=False, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_conversation_events_event_type'), 'conversation_events', ['event_type'], unique=False, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_conversation_events_received_at'), 'conversation_events', ['received_at'], unique=False, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_conversation_events_test_column'), 'conversation_events', ['test_column'], unique=False, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_conversation_events_user_id'), 'conversation_events', ['user_id'], unique=False, schema='testghostagent')
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='testghostagent'
    )
    op.create_index(op.f('ix_testghostagent_permissions_code'), 'permissions', ['code'], unique=True, schema='testghostagent')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='testghostagent'
    )
    op.create_index(op.f('ix_testghostagent_roles_name'), 'roles', ['name'], unique=True, schema='testghostagent')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='testghostagent'
    )
    op.create_index(op.f('ix_testghostagent_users_email'), 'users', ['email'], unique=True, schema='testghostagent')
    op.create_table('compliance_policy_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='policy_set_status', schema='testghostagent'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['testghostagent.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testghostagent'
    )
    op.create_index(op.f('ix_testghostagent_compliance_policy_sets_created_by'), 'compliance_policy_sets', ['created_by'], unique=False, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_compliance_policy_sets_status'), 'compliance_policy_sets', ['status'], unique=False, schema='testghostagent')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['testghostagent.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['testghostagent.roles.id'], ondelete='CASCADE'),
    schema='testghostagent'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['testghostagent.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['testghostagent.users.id'], ondelete='CASCADE'),
    schema='testghostagent'
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('access_token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['testghostagent.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='testghostagent'
    )
    op.create_index(op.f('ix_testghostagent_user_tokens_access_token'), 'user_tokens', ['access_token'], unique=True, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_user_tokens_access_token_expiry'), 'user_tokens', ['access_token_expiry'], unique=False, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_user_tokens_is_revoked'), 'user_tokens', ['is_revoked'], unique=False, schema='testghostagent')
    op.create_index(op.f('ix_testghostagent_user_tokens_refresh_token'), 'user_tokens', ['refresh_token'], unique=True, schema='testghostagent')
    op.create_table('compliance_policy_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_set_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_set_id'], ['testghostagent.compliance_policy_sets.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['testghostagent.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testghostagent'
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_set_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('rule_type', sa.Enum('do', 'dont', name='rule_type_enum', schema='testghostagent'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_enum', schema='testghostagent'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('example_snippets', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['testghostagent.users.id'], ),
    sa.ForeignKeyConstraint(['policy_set_id'], ['testghostagent.compliance_policy_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='testghostagent'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_rules', schema='testghostagent')
    op.drop_table('compliance_policy_documents', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_user_tokens_refresh_token'), table_name='user_tokens', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_user_tokens_is_revoked'), table_name='user_tokens', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_user_tokens_access_token_expiry'), table_name='user_tokens', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_user_tokens_access_token'), table_name='user_tokens', schema='testghostagent')
    op.drop_table('user_tokens', schema='testghostagent')
    op.drop_table('user_roles', schema='testghostagent')
    op.drop_table('role_permissions', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_compliance_policy_sets_status'), table_name='compliance_policy_sets', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_compliance_policy_sets_created_by'), table_name='compliance_policy_sets', schema='testghostagent')
    op.drop_table('compliance_policy_sets', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_users_email'), table_name='users', schema='testghostagent')
    op.drop_table('users', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_roles_name'), table_name='roles', schema='testghostagent')
    op.drop_table('roles', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_permissions_code'), table_name='permissions', schema='testghostagent')
    op.drop_table('permissions', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_conversation_events_user_id'), table_name='conversation_events', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_conversation_events_test_column'), table_name='conversation_events', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_conversation_events_received_at'), table_name='conversation_events', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_conversation_events_event_type'), table_name='conversation_events', schema='testghostagent')
    op.drop_index(op.f('ix_testghostagent_conversation_events_conversation_id'), table_name='conversation_events', schema='testghostagent')
    op.drop_index('idx_user_conversation', table_name='conversation_events', schema='testghostagent')
    op.drop_table('conversation_events', schema='testghostagent')
    # ### end Alembic commands ###