
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    

    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}  
    depends_on:
      - redis

